-- # LISTANDO TODOS OS DEPARTAMENTOS QUE POSSUEM FUNCIONÁRIOS E AQUELES QUE NÃO TIVEREM FUNCIONÁRIOS SERÃO EXIBIDOS COMO 'NULL'
SELECT 
    F.NOME,
    D.NOME
FROM DEPARTAMENTOS D
LEFT JOIN FUNCIONARIOS F
ON F.ID_DEPARTAMENTO = D.ID;

-- # LISTANDO TODOS OS FUNCIONÁRIOS NOME, SALÁRIO E NÍVEL DE ACORDO COM SALÁRIO
SELECT 
    F.NOME,
    F.SALARIO,
    NS.NIVEL
FROM FUNCIONARIOS F 
LEFT JOIN NIVEL_SALARIO NS ON F.SALARIO 
BETWEEN NS.SALARIO_MIN AND NS.SALARIO_MAX;

-- # LISTANDO TODOS OS FUNCIONÁRIOS DO DEPARTAMENTO DE 'VENDAS' QUE SÃO TITULADOS COMO 'PLENO'
SELECT 
    F.NOME AS FUNCIONARIO,
    D.NOME AS DEPARTAMENTO,
    NS.NIVEL 
FROM FUNCIONARIOS F
JOIN DEPARTAMENTOS D ON F.ID_DEPARTAMENTO = D.ID
JOIN NIVEL_SALARIO NS ON F.SALARIO BETWEEN NS.SALARIO_MIN AND NS.SALARIO_MAX
WHERE NS.NIVEL = 'PLENO' AND D.NOME = 'VENDAS';


